### ISSUE TITLE
molgenis_compute.sh refers to invalid jar and invalid package

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis-compute#182]
https://github.com/molgenis/molgenis-compute/blob/v15.07.3/molgenis-compute-core/src/main/resources/molgenis_compute.sh:
- refers to molgenis-compute-core-1.1.0-SNAPSHOT instead of molgenis-compute-core-1.1.0
- refers to org.molgenis.compute5.ComputeCommandLine instead of org.molgenis.compute.ComputeCommandLine

**Comment by mmterpstra** [comment]
edit and test:
https://github.com/molgenis/molgenis-compute/blob/master/molgenis-app-compute-db/src/main/resources/scripts/molgenis_compute.sh
