### ISSUE TITLE
molgenis_compute.sh is generated with an incorrect java class name

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis-compute#185]
## Bug

In the generated bash script the class that is called is org.molgenis.compute5.ComputeCommandLine.

This should be org.molgenis.compute.ComputeCommandLine

## Impact

This Bug renders the molgenis_compute.sh script unusable

Currently on the cluster there probably still exists an older version of the compiled java class.
However, with a new release/build the script can not be used.

**Comment by dennishendriksen** [comment]
Same as #182?

**Comment by Mark-de-Haan** [comment]
Yes xD
