### ISSUE TITLE
bash submit.sh gives the error jobName: unbound variable

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis-compute#283]
I changed from Molgenis-Compute v16.04.1 to v19.01.1. I kept parameters, workflow and samplesheet the same. For v16 it works, for v19 I get:

```
INFO: Changing working directory to /groups/umcg-biogen/tmp01/input/rawdata/AMP_AD/pipelines/no_patch_chromosomes/alignment/batch10... done.
submit.sh: line 56: jobName: unbound variable
```

It happens in the function processJob()

```
function processJob () {
    local _jobName="${1}"
    local _jobScript="${jobName}.sh"
```

Outside of that location jobName is not set or used. I assume I have to change something in parameters/samplesheet/workflow, but can not find in https://rawgit.com/molgenis/molgenis-compute/master/molgenis-compute-core/README.html what changes I should make.

**Comment by pneerincx** [comment]
I think you found a silly bug. You can create a copy of the submit.ftl and change
```local _jobScript="${jobName}.sh"```
into
```local _jobScript="${_jobName}.sh"```
and then specify on the commandline for compute that you want to use a custom submit template. I think the production pipelines we routinely use also use a custom template and therefore we did not notice the missing underscore in the default template.
